import SideBar from "@/components/ui/side_bar";
import clsx from "clsx";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import React from "react";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          poppins.className,
          "bg-background min-h-full text-grey-100"
        )}
      >
        <SideBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
